require 'rake/clean'

FILES = {
  'rot13' => ['rot13.cpp']
}

CLEAN << FILES.keys

GCC = 'gcc -std=c++11 -g -Wall -lstdc++'

FILES.each do |target, prerequisites|
  desc "Compile #{target} from #{prerequisites.join(' ')}"
  file target => prerequisites do |t|
    sh "#{GCC} #{t.prerequisites.join(' ')} -o #{t.name}"
  end
end

task default: FILES.keys
